### ISSUE TITLE
Fix DOI bug

### ISSUE THREAD

**Issue by jonearley** [mlibrary/openurlform#1]
Message from Pam Mackintosh

> I tried searching two DOIs:
> 
> 10.1111/1468-232X.00264
> 10.1001/jama.2013.4635
> 
> Both took me directly to the articles in the current version of the MGet It Citation Linker, but failed in the new form.   The new form seems to add a period to the end of the DOI.  I am not sure if that is causing the retrieval problem, but in both cases instead of getting me the article, I am told Online Access Is Not Available  and asked to try Mirlyn or ILL.

**Comment by jonearley** [comment]
Fixed

**Comment by varnum** [comment]
Both examples from the original ticket are working for me, now.
