### ISSUE TITLE
Display more information about books on disambiguation page

### ISSUE THREAD

**Issue by varnum** [mlibrary/openurlform#2]
Display, if available:
Author
Publisher
Year
Edition
ISBN

**Comment by jonearley** [comment]
![isbn](https://cloud.githubusercontent.com/assets/1678665/19400507/88172a60-9224-11e6-86ee-253aab0190d0.png)

**Comment by jonearley** [comment]
These are the available fields per items on a disambiguation page:

```
creator: 
source: Beginning JavaScript
isbn: '9780470051511'
issn: 
other: []
issue: 
volume: 
spage: 
epage: 
title: Javascript
eisbn: '9780470171370'
eissn: 
date: 
format: book
doi: 
```

Citations must be generic enough for all item types.

**Comment by jonearley** [comment]
This issue is being tracked in MGet It. Closing since issues here should be just for the openurlform.
