### ISSUE TITLE
Book Chapter DOI not working right

### ISSUE THREAD

**Issue by varnum** [mlibrary/openurlform#3]
From Kenyon:

Hello,

I checked the linker using just "portal" and got a disambiguation page but as I mention below I'm wondering if there is a problem with our disambiguation page.

When I just enter the journal title using either "portal" or "Portal" in the current interface I get a disambiguation page with links for Portal (Baltimore, Md.) (1531-2542) and for Portal (Sydney, N.S.W.). The Baltimore link leads to a menu with journal level links for ProQuest Muse and ProQuest while the Sydney link leads to a menu with a journal level link through Directory of Open Access Journals.

When I do the same thing in the new interface I also get a disambiguation page with links for Portal (Baltimore, Md.) (1531-2542) and for Portal (Sydney, N.S.W.). Looking at this I'm wondering if there is a problem with the disambiguation page. Both links lead to what appears to be the same menu with the link for Directory of Open Access Journals. Another problem is this menu is missing information. Even though the disambiguation menu showed the title "Portal" with an uppercase "P" with place of publication for both versions of Portal the menu reached from that page just has "portal." Also, the button to link to the journal has the generic "Go to Item" instead of "Go to Journal."

Below is the disambiguation page I reached by just using the journal title "portal." Is there a reason why it has genre "Article" even though I only put in a journal title:

https://dev.www.lib.umich.edu/testapp/mgetit/resolve?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=Article&sid=info%3Asid%3Alib.umich.edu&rft.title=portal

Below is the url for the menu I reached with the Portal (Baltimore, Md.) (1531-2542) link. This has jtitle Portal (Sydney, N.S.W.) and there is a rft.select field that contains Portal (Baltimore, Md.) (1531-2542) :

https://dev.www.lib.umich.edu/testapp/mgetit/resolve?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_id=&ctx_tim=2016-10-11T14%3A10%3A48-04%3A00&ctx_ver=Z39.88-2004&rft.eissn=1449-2490&rft.genre=Article&rft.jtitle=Portal+%28Sydney%2C+N.S.W.%29&rft.select=%7B%22source%22%3A%22Portal+%28Baltimore%2C+Md.%29%22%2C%22isbn%22%3Anull%2C%22issn%22%3A%221531-2542%22%2C%22eisbn%22%3Anull%2C%22eissn%22%3A%221530-7131%22%2C%22creator%22%3Anull%7D&rft.title=portal&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004

Below is the url for the menu I reached with the Portal (Sydney, N.S.W.) link:

https://dev.www.lib.umich.edu/testapp/mgetit/resolve?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_id=&ctx_tim=2016-10-11T14%3A10%3A48-04%3A00&ctx_ver=Z39.88-2004&rft.eissn=1449-2490&rft.genre=Article&rft.jtitle=Portal+%28Sydney%2C+N.S.W.%29&rft.select=%7B%22source%22%3A%22Portal+%28Sydney%2C+N.S.W.%29%22%2C%22isbn%22%3Anull%2C%22issn%22%3Anull%2C%22eisbn%22%3Anull%2C%22eissn%22%3A%221449-2490%22%2C%22creator%22%3Anull%7D&rft.title=portal&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004

**Comment by jonearley** [comment]
The openurlform constructs an OpenURL from citation information.

A disambiguation item will display a title, creator, source, date, and ISBN when that metadata is available.

**Comment by jonearley** [comment]
To me this is less an issue and more so feedback for how we have designed the disambiguation page and what metadata we have available to display.

This should be under the MGet It repo. Closing here since it's unrelated to the openurlform.
