### ISSUE TITLE
book format bug

### ISSUE THREAD

**Issue by jonearley** [mlibrary/openurlform#4]
https://dev.www.lib.umich.edu/testapp/mgetit/resolve?rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=Article&sid=info:sid:lib.umich.edu&rft_id=info:doi=10.1007/978-3-540-74055-1_3

rft_val_fmt
rft.genre

Should be book, but openurl is article

**Comment by jonearley** [comment]
Fixed

**Comment by varnum** [comment]
I'm not seeing this on production yet:
https://mgetit.lib.umich.edu/resolve?rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=Article&sid=info:sid:lib.umich.edu&rft_id=info:doi=10.1007/978-3-540-74055-1_3

## 

Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
Your link is for an Article. The DOI is for a book I believe.

**Development**
https://dev.www.lib.umich.edu/testapp/mgetit/resolve?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=Book&sid=info%3Asid%3Alib.umich.edu&rft_id=info%3Adoi%3D10.1007%2F978-3-540-74055-1_3

**Production**
https://mgetit.lib.umich.edu/resolve?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=Book&sid=info%3Asid%3Alib.umich.edu&rft_id=info%3Adoi%3D10.1007%2F978-3-540-74055-1_3

The development link works here, but not in production. I am unable to tag Albert here, so I will link him to this issue.

**Comment by jonearley** [comment]
I'm going to move this issue over to MGet It since the openurlform generates the OpenURL correctly in this case.

**Comment by jonearley** [comment]
Moved to MGet It repo: https://github.com/mlibrary/mgetit/issues/56
