### ISSUE TITLE
Add instructions to Citation Linker

### ISSUE THREAD

**Issue by varnum** [mlibrary/openurlform#6]
Add a note that says (wordsmithing invited):  

Journal pane
For best results, include at least one of journal title, ISSN, DOI or PMID.

Book pane
For best results, include at least one of book title, ISBN, or DOI.

**Comment by bnhowell** [comment]
Here's a stab at wordsmithing/typography.

Journal note:
For best results, include a **journal title**, **ISSN**, **DOI** or **PMID**

Book note:
For best results, include a **book title**, **ISBN**, or **DOI**

**Comment by varnum** [comment]
Perfect!
